### ISSUE TITLE
IP-address validation

### ISSUE THREAD

**Issue by ajamous** [palner/apiban#35]
When calling the `/check ` api endpoint and enter any value for ip-address , the API still responds with `{"ipaddress":"ok", "ID":"0"}` , 

To reproduce the issue you can call this URL `https://apiban.org/api/[APIKEY]/check/_.OR.%^_ ` note am passing `_.OR.%^_ ` as the ip-address here. 

You probably you would want to add ipv4 / ipv6 validation to the backend and return more clear error.

**Comment by fredposner** [comment]
So, check works kind of funny...

A 200 OK is sent for non-block and a 404 with `{"ipaddress":"ok", "ID":"0"}` is set for any non-block... including if you sent in something that was a domain name, non-ipaddress, or even sql injection.

This was done for (1) speed and (2) not-blocking good traffic.

Since a non-200 would be to block, the client would have to parse the error code to make sure they weren't blocking something that should not be blocked... So we could do a 400 or other 4xx error for invalid IP, but the decision was made to just be block / non-block.

I do like the idea of returning more information though (such as your invalid IP suggestion). Will do some testing to see if this has any impact on speed.
